substitutions:
  device_uppercase: Candle
  device_lowercase: candle
  neopixel_leds: "20"
  neopixel_id: rgb_light
  button_button_id: button
  button_toggle_id: ${neopixel_id}

esphome:
  name: ${device_lowercase}
  platform: ESP8266
  board: nodemcuv2

packages:
  wifi: !include common/wifi.yaml
  api: !include common/api.yaml

# These colors look really nice
# Candle stick'
#   Brightness: 60%
#   Red=35%, Green=100%, Blue=100%
#'Candle fire'
#   Brightness: 100%
#   Red=100%, Green=80%, Blue=25%
light:
  - platform: neopixelbus
    name: ${device_uppercase}
    variant: 400KBPS
    type: GRB
    pin: GPIO3
    num_leds: 20
    id: rgb_light
    default_transition_length: 0s
    internal: true
  - platform: partition
    name: "Candle fire"
    id: candle_fire
    segments:
      - id: rgb_light
        from: 17
        to: 20
    effects:
      - addressable_flicker:
          name: "candle_fire_flicker"
          intensity: 50%
    on_turn_on:
      - light.control:
          id: candle_fire
          effect: "candle_fire_flicker"
  - platform: partition
    name: "Candle stick"
    id: candle_stick
    segments:
      - id: rgb_light
        from: 0
        to: 16

# Location of my baby Heron Nicolas memorial
# from the local secrets.yaml file
sun:
  latitude: ${memorial_lat}
  longitude: ${memorial_long}
  on_sunset:
    - light.turn_on:
        id: candle_fire
        brightness: 100%
        red: 100%
        green: 80%
        blue: 25%
    - light.turn_on:
        id: candle_stick
        brightness: 60%
        red: 35%
        green: 100%
        blue: 100%
time:
  - platform: sntp
    timezone: ${timezone}

binary_sensor:
  - <<: !include common/button_light_toggle.yaml